
package com.dragome.gdx.input;

import com.badlogic.gdx.Input.Keys;
import com.badlogic.gdx.utils.IntIntMap;

/** Contains mappings of native key codes to LibGDX key codes.
 * @author MJ */
public class KeyCodes {
	public static final int KEY_ALT = 18;
	public static final int KEY_BACKSPACE = 8;
	public static final int KEY_CTRL = 17;
	public static final int KEY_DELETE = 46;
	public static final int KEY_DOWN = 40;
	public static final int KEY_END = 35;
	public static final int KEY_ENTER = 13;
	public static final int KEY_ESCAPE = 27;
	public static final int KEY_HOME = 36;
	public static final int KEY_LEFT = 37;
	public static final int KEY_PAGEDOWN = 34;
	public static final int KEY_PAGEUP = 33;
	public static final int KEY_RIGHT = 39;
	public static final int KEY_SHIFT = 16;
	public static final int KEY_TAB = 9;
	public static final int KEY_UP = 38;
	public static final int KEY_PAUSE = 19;
	public static final int KEY_CAPS_LOCK = 20;
	public static final int KEY_SPACE = 32;
	public static final int KEY_INSERT = 45;
	public static final int KEY_0 = 48;
	public static final int KEY_1 = 49;
	public static final int KEY_2 = 50;
	public static final int KEY_3 = 51;
	public static final int KEY_4 = 52;
	public static final int KEY_5 = 53;
	public static final int KEY_6 = 54;
	public static final int KEY_7 = 55;
	public static final int KEY_8 = 56;
	public static final int KEY_9 = 57;
	public static final int KEY_A = 65;
	public static final int KEY_B = 66;
	public static final int KEY_C = 67;
	public static final int KEY_D = 68;
	public static final int KEY_E = 69;
	public static final int KEY_F = 70;
	public static final int KEY_G = 71;
	public static final int KEY_H = 72;
	public static final int KEY_I = 73;
	public static final int KEY_J = 74;
	public static final int KEY_K = 75;
	public static final int KEY_L = 76;
	public static final int KEY_M = 77;
	public static final int KEY_N = 78;
	public static final int KEY_O = 79;
	public static final int KEY_P = 80;
	public static final int KEY_Q = 81;
	public static final int KEY_R = 82;
	public static final int KEY_S = 83;
	public static final int KEY_T = 84;
	public static final int KEY_U = 85;
	public static final int KEY_V = 86;
	public static final int KEY_W = 87;
	public static final int KEY_X = 88;
	public static final int KEY_Y = 89;
	public static final int KEY_Z = 90;
	public static final int KEY_LEFT_WINDOW_KEY = 91;
	public static final int KEY_RIGHT_WINDOW_KEY = 92;
	public static final int KEY_SELECT_KEY = 93;
	public static final int KEY_NUMPAD0 = 96;
	public static final int KEY_NUMPAD1 = 97;
	public static final int KEY_NUMPAD2 = 98;
	public static final int KEY_NUMPAD3 = 99;
	public static final int KEY_NUMPAD4 = 100;
	public static final int KEY_NUMPAD5 = 101;
	public static final int KEY_NUMPAD6 = 102;
	public static final int KEY_NUMPAD7 = 103;
	public static final int KEY_NUMPAD8 = 104;
	public static final int KEY_NUMPAD9 = 105;
	public static final int KEY_MULTIPLY = 106;
	public static final int KEY_ADD = 107;
	public static final int KEY_SUBTRACT = 109;
	public static final int KEY_DECIMAL_POINT_KEY = 110;
	public static final int KEY_DIVIDE = 111;
	public static final int KEY_F1 = 112;
	public static final int KEY_F2 = 113;
	public static final int KEY_F3 = 114;
	public static final int KEY_F4 = 115;
	public static final int KEY_F5 = 116;
	public static final int KEY_F6 = 117;
	public static final int KEY_F7 = 118;
	public static final int KEY_F8 = 119;
	public static final int KEY_F9 = 120;
	public static final int KEY_F10 = 121;
	public static final int KEY_F11 = 122;
	public static final int KEY_F12 = 123;
	public static final int KEY_NUM_LOCK = 144;
	public static final int KEY_SCROLL_LOCK = 145;
	public static final int KEY_SEMICOLON = 186;
	public static final int KEY_EQUALS = 187;
	public static final int KEY_COMMA = 188;
	public static final int KEY_DASH = 189;
	public static final int KEY_PERIOD = 190;
	public static final int KEY_FORWARD_SLASH = 191;
	public static final int KEY_GRAVE_ACCENT = 192;
	public static final int KEY_OPEN_BRACKET = 219;
	public static final int KEY_BACKSLASH = 220;
	public static final int KEY_CLOSE_BRACKET = 221;
	public static final int KEY_SINGLE_QUOTE = 222;

	private static final IntIntMap KEYS = new IntIntMap();

	private KeyCodes () {
	}

	static {
		KEYS.put(KEY_ALT, Keys.ALT_LEFT);
		KEYS.put(KEY_BACKSPACE, Keys.BACKSPACE);
		KEYS.put(KEY_CTRL, Keys.CONTROL_LEFT);
		KEYS.put(KEY_DELETE, Keys.DEL);
		KEYS.put(KEY_DOWN, Keys.DOWN);
		KEYS.put(KEY_END, Keys.END);
		KEYS.put(KEY_ENTER, Keys.ENTER);
		KEYS.put(KEY_ESCAPE, Keys.ESCAPE);
		KEYS.put(KEY_HOME, Keys.HOME);
		KEYS.put(KEY_LEFT, Keys.LEFT);
		KEYS.put(KEY_PAGEDOWN, Keys.PAGE_DOWN);
		KEYS.put(KEY_PAGEUP, Keys.PAGE_UP);
		KEYS.put(KEY_RIGHT, Keys.RIGHT);
		KEYS.put(KEY_SHIFT, Keys.SHIFT_LEFT);
		KEYS.put(KEY_TAB, Keys.TAB);
		KEYS.put(KEY_UP, Keys.UP);
		KEYS.put(KEY_SPACE, Keys.SPACE);
		KEYS.put(KEY_INSERT, Keys.INSERT);
		KEYS.put(KEY_0, Keys.NUM_0);
		KEYS.put(KEY_1, Keys.NUM_1);
		KEYS.put(KEY_2, Keys.NUM_2);
		KEYS.put(KEY_3, Keys.NUM_3);
		KEYS.put(KEY_4, Keys.NUM_4);
		KEYS.put(KEY_5, Keys.NUM_5);
		KEYS.put(KEY_6, Keys.NUM_6);
		KEYS.put(KEY_7, Keys.NUM_7);
		KEYS.put(KEY_8, Keys.NUM_8);
		KEYS.put(KEY_9, Keys.NUM_9);
		KEYS.put(KEY_A, Keys.A);
		KEYS.put(KEY_B, Keys.B);
		KEYS.put(KEY_C, Keys.C);
		KEYS.put(KEY_D, Keys.D);
		KEYS.put(KEY_E, Keys.E);
		KEYS.put(KEY_F, Keys.F);
		KEYS.put(KEY_G, Keys.G);
		KEYS.put(KEY_H, Keys.H);
		KEYS.put(KEY_I, Keys.I);
		KEYS.put(KEY_J, Keys.J);
		KEYS.put(KEY_K, Keys.K);
		KEYS.put(KEY_L, Keys.L);
		KEYS.put(KEY_M, Keys.M);
		KEYS.put(KEY_N, Keys.N);
		KEYS.put(KEY_O, Keys.O);
		KEYS.put(KEY_P, Keys.P);
		KEYS.put(KEY_Q, Keys.Q);
		KEYS.put(KEY_R, Keys.R);
		KEYS.put(KEY_S, Keys.S);
		KEYS.put(KEY_T, Keys.T);
		KEYS.put(KEY_U, Keys.U);
		KEYS.put(KEY_V, Keys.V);
		KEYS.put(KEY_W, Keys.W);
		KEYS.put(KEY_X, Keys.X);
		KEYS.put(KEY_Y, Keys.Y);
		KEYS.put(KEY_Z, Keys.Z);
		KEYS.put(KEY_NUMPAD0, Keys.NUMPAD_0);
		KEYS.put(KEY_NUMPAD1, Keys.NUMPAD_1);
		KEYS.put(KEY_NUMPAD2, Keys.NUMPAD_2);
		KEYS.put(KEY_NUMPAD3, Keys.NUMPAD_3);
		KEYS.put(KEY_NUMPAD4, Keys.NUMPAD_4);
		KEYS.put(KEY_NUMPAD5, Keys.NUMPAD_5);
		KEYS.put(KEY_NUMPAD6, Keys.NUMPAD_6);
		KEYS.put(KEY_NUMPAD7, Keys.NUMPAD_7);
		KEYS.put(KEY_NUMPAD8, Keys.NUMPAD_8);
		KEYS.put(KEY_NUMPAD9, Keys.NUMPAD_9);
		KEYS.put(KEY_ADD, Keys.PLUS);
		KEYS.put(KEY_SUBTRACT, Keys.MINUS);
		KEYS.put(KEY_DECIMAL_POINT_KEY, Keys.PERIOD);
		KEYS.put(KEY_F1, Keys.F1);
		KEYS.put(KEY_F2, Keys.F2);
		KEYS.put(KEY_F3, Keys.F3);
		KEYS.put(KEY_F4, Keys.F4);
		KEYS.put(KEY_F5, Keys.F5);
		KEYS.put(KEY_F6, Keys.F6);
		KEYS.put(KEY_F7, Keys.F7);
		KEYS.put(KEY_F8, Keys.F8);
		KEYS.put(KEY_F9, Keys.F9);
		KEYS.put(KEY_F10, Keys.F10);
		KEYS.put(KEY_F11, Keys.F11);
		KEYS.put(KEY_F12, Keys.F12);
		KEYS.put(KEY_NUM_LOCK, Keys.NUM);
		KEYS.put(KEY_SELECT_KEY, Keys.BUTTON_SELECT);
		KEYS.put(KEY_SEMICOLON, Keys.SEMICOLON);
		KEYS.put(KEY_EQUALS, Keys.EQUALS);
		KEYS.put(KEY_COMMA, Keys.COMMA);
		KEYS.put(KEY_DASH, Keys.MINUS);
		KEYS.put(KEY_PERIOD, Keys.PERIOD);
		KEYS.put(KEY_FORWARD_SLASH, Keys.SLASH);
		KEYS.put(KEY_OPEN_BRACKET, Keys.LEFT_BRACKET);
		KEYS.put(KEY_BACKSLASH, Keys.BACKSLASH);
		KEYS.put(KEY_CLOSE_BRACKET, Keys.RIGHT_BRACKET);
		KEYS.put(KEY_SINGLE_QUOTE, Keys.APOSTROPHE);
		KEYS.put(KEY_GRAVE_ACCENT, Keys.GRAVE);
		KEYS.put(KEY_MULTIPLY, Keys.STAR);
		KEYS.put(KEY_DIVIDE, Keys.SLASH);
		KEYS.put(KEY_CAPS_LOCK, Keys.UNKNOWN);
		KEYS.put(KEY_PAUSE, Keys.UNKNOWN);
		KEYS.put(KEY_LEFT_WINDOW_KEY, Keys.UNKNOWN);
		KEYS.put(KEY_RIGHT_WINDOW_KEY, Keys.UNKNOWN);
		KEYS.put(KEY_SCROLL_LOCK, Keys.UNKNOWN);
	}

	/** @param keyCode key code returned from the JavaScript event.
	 * @return a corresponding value from {@link Keys} class or {@link Keys#UNKNOWN} if key code is not supported. */
	public static int toKey (final int keyCode) {
		return KEYS.get(keyCode, Keys.UNKNOWN);
	}
}
